// <auto-generated />
namespace MeHospedar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class base141 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(base141));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121514059_base141"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
